name: Deployer

on:
  push:
    branches: [main, cicd]

concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
  
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer:v2, deployer:7.0.1
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: |
        ssh-keyscan -H ${{ secrets.REMOTE_IP }} >> ~/.ssh/known_hosts
    - name: Composer
      run: |
        cd www && ls -la
        composer install
        deployer deploy develop